bootstrap: .codex/bootstrap.sh
image: ghcr.io/<OWNER>/ytapp-dev:latest
workflow:
  default:
    - description: "Run unit & CLI tests"
      run: |
        cd ytapp
        npx ts-node tests/csv.test.ts
        npx ts-node tests/upload.test.ts
