#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

os="$(uname -s)"
case "$os" in
    Linux*) PLATFORM=linux ;;
    Darwin*) PLATFORM=mac ;;
    MINGW*|MSYS*|CYGWIN*|Windows_NT*) PLATFORM=windows ;;
    *) PLATFORM=unknown ;;
esac

echo "Detected OS: $PLATFORM"

install_rust() {
    if ! command -v rustup >/dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
            sh -s -- -y --profile minimal
        export PATH="$HOME/.cargo/bin:$PATH"
    fi
    rustup toolchain install stable
    rustup default stable
}

install_node() {
    if ! command -v node >/dev/null || ! node -v | grep -q '^v20'; then
        case "$PLATFORM" in
            linux)
                curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                sudo apt-get install -y nodejs
                ;;
            mac)
                if command -v brew >/dev/null; then
                    brew install node@20
                    brew link --overwrite --force node@20
                fi
                ;;
            windows)
                if command -v choco >/dev/null; then
                    choco install -y nodejs-lts
                fi
                ;;
        esac
    fi
    corepack enable
}

install_ffmpeg() {
    if ! command -v ffmpeg >/dev/null; then
        case "$PLATFORM" in
            linux)
                sudo apt-get update && sudo apt-get install -y ffmpeg
                ;;
            mac)
                command -v brew >/dev/null && brew install ffmpeg
                ;;
            windows)
                if command -v choco >/dev/null; then
                    choco install -y ffmpeg
                fi
                ;;
        esac
    fi
}

install_whisper_model() {
    local base_dir="${XDG_CACHE_HOME:-$HOME/.cache}"
    local dir="$base_dir/whisper"
    local model="$dir/ggml-base.bin"
    if [ ! -f "$model" ]; then
        mkdir -p "$dir"
        curl -L https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin -o "$model"
    fi
}

if [ "$PLATFORM" = linux ]; then
    "$ROOT_DIR/scripts/install_tauri_deps.sh"
    source "$ROOT_DIR/.env.tauri"
    PKG_CONFIG_PATH_VALUE="$(cut -d= -f2 "$ROOT_DIR/.env.tauri")"
elif [ "$PLATFORM" = mac ]; then
    install_ffmpeg
    install_node
    install_rust
    PKG_CONFIG_PATH_VALUE="/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig"
else
    install_node
    install_rust
fi

install_ffmpeg
install_node
install_rust
install_whisper_model

echo "# Generated by scripts/bootstrap.sh" > "$ENV_FILE"
if [ -n "${PKG_CONFIG_PATH_VALUE:-}" ]; then
    echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH_VALUE" >> "$ENV_FILE"
fi

echo "Bootstrap complete. Environment variables written to $ENV_FILE"
