name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('ytapp/src-tauri/Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: ytapp/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('ytapp/package-lock.json') }}
      - uses: devcontainers/ci@v0.3
        with:
          imageName: devcontainer-image
          cacheFrom: ghcr.io/${{ github.repository_owner }}/ytapp-devcontainer:latest
          push: false
          runCmd: |
            make dev
            make test
