name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo + rustup
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ytapp/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('ytapp/package-lock.json') }}
      - run: ./scripts/setup.sh
      - run: make verify
