name: Package
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/package.sh
      - uses: actions/upload-artifact@v4
        with:
          name: installers
          path: dist/*
